export default {
  borderTopRightRadius: null,
  backfaceVisibility: null,
  borderBottomLeftRadius: null,
  borderBottomRightRadius: null,
  borderColor: null,
  borderRadius: null,
  borderTopLeftRadius: null,
  backgroundColor: null,
  borderWidth: null,
  opacity: null,
  overflow: null,
  resizeMode: null,
  tintColor: null,
  overlayColor: null,
}