export default {
  textShadowOffset: null,
  color: null,
  fontSize: null,
  fontStyle: null,
  fontWeight: null,
  lineHeight: null,
  textAlign: null,
  textDecorationLine: null,
  textShadowColor: null,
  fontFamily: null,
  textShadowRadius: null,
  includeFontPadding: null,
  textAlignVertical: null,
  fontVariant: null,
  letterSpacing: null,
  textDecorationColor: null,
  textDecorationStyle: null,
  writingDirection: null,
}