import View from './View';

const ScrollView = {
  ...View,
  alwaysBounceVertical: null,
  contentContainerStyle: null,
  keyboardDismissMode: null,
  keyboardShouldPersistTaps: null,
  onContentSizeChange: null,
  onMomentumScrollBegin: null,
  onMomentumScrollEnd: null,
  onScroll: null,
  pagingEnabled: null,
  refreshControl: null,
  removeClippedSubviews: null,
  scrollEnabled: null,
  showsHorizontalScrollIndicator: null,
  showsVerticalScrollIndicator: null,
  stickyHeaderIndices: null,
  endFillColor: null,
  overScrollMode: null,
  scrollPerfTag: null,
  alwaysBounceHorizontal: null,
  horizontal: null,
  automaticallyAdjustContentInsets: null,
  bounces: null,
  bouncesZoom: null,
  canCancelContentTouches: null,
  centerContent: null,
  contentInset: null,
  contentInsetAdjustmentBehavior: null,
  contentOffset: null,
  decelerationRate: null,
  directionalLockEnabled: null,
  indicatorStyle: null,
  maximumZoomScale: null,
  minimumZoomScale: null,
  pinchGestureEnabled: null,
  scrollEventThrottle: null,
  scrollIndicatorInsets: null,
  scrollsToTop: null,
  snapToAlignment: null,
  snapToInterval: null,
  zoomScale: null,
};

export default ScrollView;
